version: "2"
services:
#  web:
#    build: .
#    container_name: "City_Web_App"
#    command: npm run dev
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_HOST=db
#    restart: always
#    volumes:
#      - .:/usr/app/
#      - /usr/app/node_modules
  db:
    image: mysql:5.7
    container_name: "MySQL_Database_Node"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - "db:MySQL_Database_Node"
    ports:
      - 8080:80
    volumes:
      - /sessions